version: '3'

services:
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    volumes:
      - ollama_data:/root/.ollama
    ports:
      - "11434:11434"
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: nvidia
    #           count: all
    #           capabilities: [ gpu ]

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: chatbot-agent-ai
    environment:
      - OLLAMA_HOST=localhost
      - OLLAMA_PORT=11434
      - OLLAMA_MODEL=llama3.2:latest
      - DEFAULT_MODEL=llama3.2:latest
    ports:
      - "8000:8000"
    depends_on:
      - ollama

volumes:
  ollama_data:
